<?php

namespace SimplonV\BusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BusStopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusStopRepository extends EntityRepository
{
}
