simplon_v_bus_user:
    resource: "@SimplonVBusBundle/Resources/config/routing/user.yml"
    prefix:   /user

simplon_v_bus_busstop:
    resource: "@SimplonVBusBundle/Resources/config/routing/busstop.yml"
    prefix:   /busstop

simplon_v_bus_inscription:
     resource: "@SimplonVBusBundle/Resources/config/routing/inscription.yml"
     prefix:   /inscription

simplon_v_bus_homepage:
    path:     /
    defaults: { _controller: SimplonVBusBundle:Default:index }

login:
    pattern:   /login
    defaults:  { _controller: SimplonVBusBundle:Default:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout



