services:
  simplonv.bus.admin.category:
    class: SimplonV\BusBundle\Admin\BusStopAdmin
    tags:
        - { name: sonata.admin, manager_type: orm, group: bus, label: busstop }
    arguments: [null, SimplonV\BusBundle\Entity\BusStop, SimplonVBusBundle:BusStopAdmin]