<?php

namespace Acme\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Arret_busRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Arret_busRepository extends EntityRepository
{
}
