SimplonV\BusBundle\Entity\kid:
    type: entity
    table: null
    repositoryClass: SimplonV\BusBundle\Entity\kidRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        date:
            type: string
            length: 255
        ecole:
            type: string
            length: 255
        classe:
            type: string
            length: 255
        adresse:
            type: string
            length: 255
        circuit:
            type: string
            length: 255
    lifecycleCallbacks: {  }
