Acme\DemoBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Acme\DemoBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        'dateFieldType[string]:':
            type: datetime
            column: 'date Field type [string]:'
        'titleFieldType[string]:String':
            type: string
            length: 255
            column: 'title Field type [string]: string'
        'authorFieldType[string]:':
            type: string
            length: '255'
            column: 'author Field type [string]:'
        'contentFieldType[string]:':
            type: text
            column: 'content Field type [string]:'
    lifecycleCallbacks: {  }
